### ISSUE TITLE
可否让content属性支持组件

### ISSUE THREAD

**Issue by crazyurus** [qiheng/vue2-layer-mobile#1]
content目前只支持字符串，传入html不太方便

**Comment by qiheng** [comment]
请升级最新版本，github有API说明,支持组件式使用

**Comment by crazyurus** [comment]
不是指slot那种方式，是想说类似于这个项目：[vue-layer](https://github.com/zuoyanart/vue-layer)
这种形式：
```
layer.iframe({
  content: {
    content: componentName, //传递的组件对象
    parent: this,//当前的vue对象
    data:[]//props
  }
});
```

**Comment by qiheng** [comment]
@crazyurus 这个目前还没有支持，下个版本可以考虑加入此项功能；目前你只能暂时使用slot来实现功能
