### ISSUE TITLE
怎么把time自动关闭的功能注释掉了?是有什么bug吗?

### ISSUE THREAD

**Issue by Sweet-KK** [qiheng/vue2-layer-mobile#2]
如题

**Comment by qiheng** [comment]
@Sweet-KK 你用的是哪个方法，方便贴下代码吗？

**Comment by Sweet-KK** [comment]
> @Sweet-KK 你用的是哪个方法，方便贴下代码吗？

msg方法传入time参数的时候由于代码注释了,因此自动关闭无效

**Comment by qiheng** [comment]
@Sweet-KK 哦，你说的是我的源码啊，没有bug啊。具体你可以仔细研读
